version: "3.8"

services:
  mysql_db:
    image: mysql:latest # 指定版本号
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: "123456" # 设置root密码
    ports:
      - "3306:3306" # 端口映射: 宿主机端口:容器端口
    volumes:
      - mysql_data:/Users/spark/Documents/mysql-data # 数据持久化
    restart: always # 自动重启

volumes:
  mysql_data: # 命名卷，用于持久化存储数据
